name: djangoapiserver CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-lastest

  steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2
    
    - name: Set Up Python 3.13
      uses: actions/setpu-python@v4
      with:
        python-version: 3.13
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}